### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by roblabla** [bozaro/lz4-rs#33]
Heyo,

I'm planning on releasing a tool that uses the lz4-rs block-compression module, which is unreleased on crates.io yet. Because crates.io doesn't allow git dependencies, I'm currently stuck. Is there any plans on making a new release to make those functions available to crates.io users ? Anything I can do to help ?

Thanks for the great dependency :)

**Comment by jheyens** [comment]
Yeah, I probably should do that.

I'm contacting @bozaro to get access to the package on crates.io.
Expect a new version in the next few days.

**Comment by jheyens** [comment]
[v1.23.0 ](https://crates.io/crates/lz4) is available on crates.io.
