### ISSUE TITLE
Looking for new maintainer

### ISSUE THREAD

**Issue by jheyens** [bozaro/lz4-rs#52]
Dear users,

I am sorry I didn't live up to the promises I made in some of the issues and pull requests. My intention was not to deceive you, but to actually continue working on this library and to let this be my small contribution to the Rust community. 
However, I don't want to make any more empty promises, I won't fulfill, so I am now looking for a new maintainer for this library.

My plan forward would be to give contributor access to a volunteer, but I just noticed, I can't even do that, since I am not a maintainer of this Github project. If someone volunteers, we should migrate to another namespace.

Regarding the crates.io access rights, I would suggest doing the updates myself for a transitioning period to ensure the new maintainer does not have any malicious intentions.

Cheers,
Jens

**Comment by pmarks** [comment]
@jheyens Thanks for your work on `lz4-rs`!  We (@10xGenomics) use this crate extensively and have 3-4 Rust developers with experience maintaining public crates. That said, we are not experts on compression. We'd be willing to take over maintenance unless there's another group that's highly motivated to take over.

**Comment by jheyens** [comment]
This sounds really great!

I am going to write you an email for further steps

edit: Done.

**Comment by jheyens** [comment]
@10XGenomics has volunteered to take over this library.

The new project home (due to having the wrong github permissions) will be at https://github.com/10XGenomics/lz4-rs

**Comment by fanatid** [comment]
Can you put notion to README.md that project at https://github.com/bozaro/lz4-rs not maintained anymore and new address https://github.com/10XGenomics/lz4-rs ?

It's was hard to find such info.
Thanks!

**Comment by fanatid** [comment]
@pmarks @10XGenomics Out of interest, why issue section not available in your fork?

**Comment by pmarks** [comment]
@fanatid thanks - I noted the move in the README on 10xGenomics.  Wea re trying to transfer this repo to that organization which will preserve the issue history.
